services:
  # Backend Service
  - type: web
    name: gudmed-backend
    rootDir: backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://gudmed.vercel.app
      - key: ADMIN_URL
        value: https://gudmed-admin.vercel.app
    healthCheckPath: /api/health
    autoDeploy: true
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      - type: rewrite
        source: /socket.io/*
        destination: /socket.io/$1

  # Frontend Service
  - type: web
    name: gudmed-frontend
    rootDir: frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://gudmed-backend.onrender.com
      - key: REACT_APP_SOCKET_URL
        value: https://gudmed-backend.onrender.com
      - key: REACT_APP_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Admin Dashboard Service
  - type: web
    name: gudmed-admin
    rootDir: admin-dashboard
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://gudmed-backend.onrender.com
      - key: REACT_APP_SOCKET_URL
        value: https://gudmed-backend.onrender.com
      - key: REACT_APP_ENV
        value: production
      - key: PORT
        value: 3001
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 