services:
  - type: web
    name: gudmed-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://your-frontend.vercel.app
      - key: ADMIN_URL
        value: https://your-admin.vercel.app
    healthCheckPath: /api/health
    autoDeploy: true 